//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidderInfo
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> ConstructionProjectId { get; set; }
        public string BidName { get; set; }
        public string BidAuthorizer { get; set; }
        public Nullable<double> BidTotal { get; set; }
        public string BidCompiler { get; set; }
        public string BidCompilerCertNo { get; set; }
        public string BidCompileDate { get; set; }
        public string BidExaminer { get; set; }
        public string BidExaminerCertNo { get; set; }
        public string BidExamineDate { get; set; }
        public string BidApprover { get; set; }
        public string BidApproverCertNo { get; set; }
        public string BidApproveDate { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
