//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionProjectsAddType
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public Nullable<int> ProjectClasses { get; set; }
        public Nullable<int> SurfaceLeve { get; set; }
        public Nullable<int> UndergroundLeve { get; set; }
        public Nullable<int> StructureType { get; set; }
        public Nullable<int> BasisType { get; set; }
        public Nullable<int> Intensity { get; set; }
        public Nullable<int> FinishBz { get; set; }
    }
}
