//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionProjects
    {
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public Nullable<int> FileKind { get; set; }
        public Nullable<int> ValuationMethod { get; set; }
        public Nullable<int> TaxModel { get; set; }
        public string StandardName { get; set; }
        public string StandardNumber { get; set; }
        public string Scale { get; set; }
        public string Explains { get; set; }
        public string Owner { get; set; }
        public string ProvinceId { get; set; }
        public string CityId { get; set; }
        public string AreaType { get; set; }
        public string ProjectType { get; set; }
        public Nullable<int> State { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public Nullable<System.DateTime> MakeDate { get; set; }
        public Nullable<System.Guid> BelongUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ProjectFeatureId { get; set; }
        public string ProjectFeatureName { get; set; }
        public string XmlUrl { get; set; }
        public string XmlFileName { get; set; }
        public Nullable<int> BuildType { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string RejectReason { get; set; }
        public string CountyId { get; set; }
        public string RejectMark { get; set; }
        public Nullable<int> CompanyAuditState { get; set; }
        public string CompanyReason { get; set; }
        public Nullable<int> SendState { get; set; }
        public string ScaleValue { get; set; }
        public string ScaleUnit { get; set; }
        public Nullable<int> DataTBState { get; set; }
        public Nullable<System.Guid> HistoryProjectId { get; set; }
        public string MaterialPriceDate { get; set; }
        public string ScaleUnitNew { get; set; }
        public Nullable<System.DateTime> FileMakeDate { get; set; }
        public Nullable<System.Guid> HTID { get; set; }
        public string XmlName { get; set; }
        public string ValuationMethodReason { get; set; }
        public Nullable<int> AutoResolveState { get; set; }
        public Nullable<System.Guid> OaId { get; set; }
        public string ScaleUnit1 { get; set; }
        public Nullable<int> WarningState { get; set; }
        public Nullable<int> SendState1 { get; set; }
        public string ScaleValue1 { get; set; }
        public Nullable<int> DataTBState1 { get; set; }
        public Nullable<System.Guid> HistoryProjectId1 { get; set; }
        public Nullable<System.Guid> HTID1 { get; set; }
        public string XmlName1 { get; set; }
        public string ValuationMethodReason1 { get; set; }
        public Nullable<int> AutoResolveState1 { get; set; }
        public Nullable<int> WarningState1 { get; set; }
        public Nullable<int> FileAutoState { get; set; }
    }
}
