//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayWorkRateItem
    {
        public System.Guid Id { get; set; }
        public System.Guid DayWorkRateGroupId { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Specification { get; set; }
        public string Unit { get; set; }
        public double ProvisionalQuantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Total { get; set; }
        public string Remark { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> ProvisionalTotal { get; set; }
        public Nullable<System.Guid> MainProjectId { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
