//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressElement
    {
        public System.Guid Id { get; set; }
        public System.Guid ExpItemFatherId { get; set; }
        public string FatherNodeName { get; set; }
        public string OrderNumber { get; set; }
        public string Express { get; set; }
        public double Quantity { get; set; }
        public string Remark { get; set; }
        public int Kind { get; set; }
        public Nullable<System.Guid> MainProjectId { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
