//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryRecord
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TableId { get; set; }
        public Nullable<double> EditBefore { get; set; }
        public Nullable<double> EditLater { get; set; }
        public Nullable<System.Guid> EditorId { get; set; }
        public string EditorName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string Remark { get; set; }
    }
}
