//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabourMachinesSummary
    {
        public System.Guid ProjectId { get; set; }
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Specification { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string ProviderRate { get; set; }
        public Nullable<double> ProviderBase { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> NoTaxOrgPrice { get; set; }
        public Nullable<double> NoTaxPrice { get; set; }
        public Nullable<double> TaxOrgPrice { get; set; }
        public Nullable<double> TaxPrice { get; set; }
        public Nullable<double> NoTaxOrgTotal { get; set; }
        public Nullable<double> NoTaxTotal { get; set; }
        public Nullable<double> TaxOrgTotal { get; set; }
        public Nullable<double> TaxTotal { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> BasicPrice { get; set; }
        public Nullable<double> CurrentPrice { get; set; }
        public Nullable<int> Kind { get; set; }
        public string Class { get; set; }
        public Nullable<int> ExtKind { get; set; }
        public Nullable<bool> Concrete { get; set; }
        public string AddiKind { get; set; }
        public Nullable<bool> MainMaterial { get; set; }
        public Nullable<bool> ProvisionalMaterial { get; set; }
        public Nullable<int> Provider { get; set; }
        public string Delivery { get; set; }
        public string Location { get; set; }
        public string ProducingArea { get; set; }
        public string Supplier { get; set; }
        public string Character { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> MainProjectId { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
