//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabourMaterialsEquipmentsMachinesElement
    {
        public System.Guid Id { get; set; }
        public System.Guid LMEMS_ID { get; set; }
        public string Number { get; set; }
        public double Quantity { get; set; }
        public bool NOCost { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
