//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PriceMonitoring2V2Entities : DbContext
    {
        public PriceMonitoring2V2Entities()
            : base("name=PriceMonitoring2V2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AddiCost> AddiCost { get; set; }
        public DbSet<AddInfoItem> AddInfoItem { get; set; }
        public DbSet<AttrInfoItem> AttrInfoItem { get; set; }
        public DbSet<BidderInfo> BidderInfo { get; set; }
        public DbSet<BidEvaluationMainMaterial> BidEvaluationMainMaterial { get; set; }
        public DbSet<ClaimsCostGroup> ClaimsCostGroup { get; set; }
        public DbSet<ClaimsCostItem> ClaimsCostItem { get; set; }
        public DbSet<ConstructionCost> ConstructionCost { get; set; }
        public DbSet<ConstructionProjects> ConstructionProjects { get; set; }
        public DbSet<ConstructionProjectsAddType> ConstructionProjectsAddType { get; set; }
        public DbSet<ConstructionProjectsStaffInfo> ConstructionProjectsStaffInfo { get; set; }
        public DbSet<ContingencyFee> ContingencyFee { get; set; }
        public DbSet<ContingencyFeeGroup> ContingencyFeeGroup { get; set; }
        public DbSet<ContingencyFeeItem> ContingencyFeeItem { get; set; }
        public DbSet<CostItem> CostItem { get; set; }
        public DbSet<DayWorkRateGroup> DayWorkRateGroup { get; set; }
        public DbSet<DayWorkRateItem> DayWorkRateItem { get; set; }
        public DbSet<DivisionalWorks> DivisionalWorks { get; set; }
        public DbSet<EquipmentProcurementCost> EquipmentProcurementCost { get; set; }
        public DbSet<EquipmentProcurementCostItem> EquipmentProcurementCostItem { get; set; }
        public DbSet<ExpressElement> ExpressElement { get; set; }
        public DbSet<HistoryRecord> HistoryRecord { get; set; }
        public DbSet<LabourMachinesSummary> LabourMachinesSummary { get; set; }
        public DbSet<LabourMachinesType> LabourMachinesType { get; set; }
        public DbSet<LabourMaterialsEquipmentsMachinesElement> LabourMaterialsEquipmentsMachinesElement { get; set; }
        public DbSet<MachinesTypeInfo> MachinesTypeInfo { get; set; }
        public DbSet<MainContractorAttendanceGroup> MainContractorAttendanceGroup { get; set; }
        public DbSet<MainContractorAttendanceItem> MainContractorAttendanceItem { get; set; }
        public DbSet<Options> Options { get; set; }
        public DbSet<OtherCost> OtherCost { get; set; }
        public DbSet<OtherCostGroup> OtherCostGroup { get; set; }
        public DbSet<OtherCostItem> OtherCostItem { get; set; }
        public DbSet<OtherCostSums> OtherCostSums { get; set; }
        public DbSet<PreliminariesItemsByTotal> PreliminariesItemsByTotal { get; set; }
        public DbSet<ProjectInfo> ProjectInfo { get; set; }
        public DbSet<ProjectInstallationWorkCost> ProjectInstallationWorkCost { get; set; }
        public DbSet<ProjectType> ProjectType { get; set; }
        public DbSet<ProportionInfo> ProportionInfo { get; set; }
        public DbSet<ProvisionalMaterialGroup> ProvisionalMaterialGroup { get; set; }
        public DbSet<ProvisionalMaterialItem> ProvisionalMaterialItem { get; set; }
        public DbSet<ProvisionalSumsGroup> ProvisionalSumsGroup { get; set; }
        public DbSet<ProvisionalSumsItem> ProvisionalSumsItem { get; set; }
        public DbSet<SeasonConfig> SeasonConfig { get; set; }
        public DbSet<SiteInstructionCostGroup> SiteInstructionCostGroup { get; set; }
        public DbSet<SiteInstructionCostItem> SiteInstructionCostItem { get; set; }
        public DbSet<SpecialtyProvisionalPriceGroup> SpecialtyProvisionalPriceGroup { get; set; }
        public DbSet<SpecialtyProvisionalPriceItem> SpecialtyProvisionalPriceItem { get; set; }
        public DbSet<SpecifyCostCostItem> SpecifyCostCostItem { get; set; }
        public DbSet<SpecifyCostGroup> SpecifyCostGroup { get; set; }
        public DbSet<SpecifyCostSum> SpecifyCostSum { get; set; }
        public DbSet<StatutoryFeesGroup> StatutoryFeesGroup { get; set; }
        public DbSet<StatutoryFeesItem> StatutoryFeesItem { get; set; }
        public DbSet<SummaryItem> SummaryItem { get; set; }
        public DbSet<SummaryOfBasicCost> SummaryOfBasicCost { get; set; }
        public DbSet<SummaryOfCost> SummaryOfCost { get; set; }
        public DbSet<SundryCostsGroup> SundryCostsGroup { get; set; }
        public DbSet<SundryCostsItem> SundryCostsItem { get; set; }
        public DbSet<SYS_Config> SYS_Config { get; set; }
        public DbSet<SYS_Config_Retrieve> SYS_Config_Retrieve { get; set; }
        public DbSet<TaxGroup> TaxGroup { get; set; }
        public DbSet<TaxItem> TaxItem { get; set; }
        public DbSet<TaxRateContrastBJ> TaxRateContrastBJ { get; set; }
        public DbSet<TendererBidderInfo> TendererBidderInfo { get; set; }
        public DbSet<UnitPriceCalculationOfItem> UnitPriceCalculationOfItem { get; set; }
        public DbSet<UnitWorks> UnitWorks { get; set; }
        public DbSet<WorkContent> WorkContent { get; set; }
        public DbSet<SystemInfo> SystemInfo { get; set; }
        public DbSet<CombinedNorm> CombinedNorm { get; set; }
        public DbSet<Norm> Norm { get; set; }
        public DbSet<SectionalWorks> SectionalWorks { get; set; }
        public DbSet<WorkElement> WorkElement { get; set; }
    }
}
