//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Options
    {
        public System.Guid Id { get; set; }
        public string ProjectNumber { get; set; }
        public int ResPrecision { get; set; }
        public int QuantityPrecision { get; set; }
        public int CostPrecision { get; set; }
        public int RatePrecision { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SortNum { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
    }
}
