//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public System.Guid Id { get; set; }
        public System.Guid ConstructionProjectId { get; set; }
        public string Designer { get; set; }
        public string Contractor { get; set; }
        public string CompileCompany { get; set; }
        public string Authorizer { get; set; }
        public string Compiler { get; set; }
        public string CompilerCertNo { get; set; }
        public string CompileDate { get; set; }
        public string Examiner { get; set; }
        public string ExaminerCertNo { get; set; }
        public string ExamineDate { get; set; }
        public string Approver { get; set; }
        public string ApproverCertNo { get; set; }
        public string ApproverDate { get; set; }
        public double Total { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
