//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryOfBasicCost
    {
        public System.Guid Id { get; set; }
        public System.Guid CostFacherId { get; set; }
        public string FatherNode { get; set; }
        public Nullable<double> Labor { get; set; }
        public Nullable<double> Material { get; set; }
        public Nullable<double> MainMaterialEquipment { get; set; }
        public Nullable<double> Machine { get; set; }
        public Nullable<double> Overhead { get; set; }
        public Nullable<double> RiskRate { get; set; }
        public Nullable<double> StatutoryFees { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<double> Appraisal { get; set; }
        public Nullable<System.Guid> MainProjectId { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
