//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryOfCost
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> DivisionalAndElementalWorks { get; set; }
        public Nullable<double> Preliminaries { get; set; }
        public Nullable<double> CostForHSE { get; set; }
        public Nullable<double> OtherPreliminaries { get; set; }
        public Nullable<double> SundryCosts { get; set; }
        public Nullable<double> ProvisionalSums { get; set; }
        public Nullable<double> ProvisionalMaterial { get; set; }
        public Nullable<double> SpecialtyProvisionalPrice { get; set; }
        public Nullable<double> DayWorkRate { get; set; }
        public Nullable<double> MainContractorAttendance { get; set; }
        public Nullable<double> ClaimForLossAndExpenses { get; set; }
        public Nullable<double> SiteInstruction { get; set; }
        public Nullable<double> StatutoryFees { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Labor { get; set; }
        public Nullable<double> Material { get; set; }
        public Nullable<double> MainMaterialEquipment { get; set; }
        public Nullable<double> MainMaterial { get; set; }
        public Nullable<double> Equipment { get; set; }
        public Nullable<double> Machine { get; set; }
        public Nullable<double> Overhead { get; set; }
        public Nullable<double> RiskRate { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<System.Guid> MainProjectId { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
