//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Config_Retrieve
    {
        public int ID { get; set; }
        public int SUB_ID { get; set; }
        public string RetrieveNumValue { get; set; }
        public string RetrieveNameValue { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ItemId { get; set; }
    }
}
