//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TendererBidderInfo
    {
        public System.Guid Id { get; set; }
        public System.Guid ConstructionProjectId { get; set; }
        public string Tenderername { get; set; }
        public string TenderAuthorizer { get; set; }
        public string TenderCompiler { get; set; }
        public string TenderCompilerCertNo { get; set; }
        public string TenderCompileDate { get; set; }
        public string TenderExaminer { get; set; }
        public string TenderExaminerCertNo { get; set; }
        public string TenderExamineDate { get; set; }
        public string TenderApprover { get; set; }
        public string TenderApproverCertNo { get; set; }
        public string TenderApproveDate { get; set; }
        public string Proxy { get; set; }
        public string ProxyCertNo { get; set; }
        public string ProxyAuthorizer { get; set; }
        public string ProxyCompiler { get; set; }
        public string ProxyCompilerCertNo { get; set; }
        public string ProxyCompileDate { get; set; }
        public string ProxyExaminer { get; set; }
        public string ProxyExaminerCertNo { get; set; }
        public string ProxyExamineDate { get; set; }
        public string ProxyApprover { get; set; }
        public string ProxyApproverCertNo { get; set; }
        public string ProxyApproveDate { get; set; }
        public string Consultant { get; set; }
        public string ConsultantCertNo { get; set; }
        public string ConsultantAuthorizer { get; set; }
        public string ConsultantCompiler { get; set; }
        public string ConsultantCompilerCertNo { get; set; }
        public string ConsultantCompileDate { get; set; }
        public string ConsultantExaminer { get; set; }
        public string ConsultantExaminerCertNo { get; set; }
        public string ConsultantExamineDate { get; set; }
        public string ConsultantApprover { get; set; }
        public string ConsultantApproverCertNo { get; set; }
        public string ConsultantApproveDate { get; set; }
        public double TenderSumLimit { get; set; }
        public string BidName { get; set; }
        public string BidAuthorizer { get; set; }
        public double BidTotal { get; set; }
        public string BidCompiler { get; set; }
        public string BidCompilerCertNo { get; set; }
        public string BidCompileDate { get; set; }
        public string BidExaminer { get; set; }
        public string BidExaminerCertNo { get; set; }
        public string BidExamineDate { get; set; }
        public string BidApprover { get; set; }
        public string BidApproverCertNo { get; set; }
        public string BidApproveDate { get; set; }
        public Nullable<int> SortNum { get; set; }
    }
}
