//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitWorks
    {
        public System.Guid SectionalWorksId { get; set; }
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Segment { get; set; }
        public int ValuationMethod { get; set; }
        public int TaxModel { get; set; }
        public Nullable<double> Total { get; set; }
        public string Specialty { get; set; }
        public string Purposes { get; set; }
        public string BillDataBase { get; set; }
        public string NormDataBase { get; set; }
        public string Remark { get; set; }
        public string Code { get; set; }
        public string Explains { get; set; }
        public string Scale { get; set; }
        public Nullable<int> SortNum { get; set; }
        public string ScaleUnit { get; set; }
    }
}
