//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkElement
    {
        public System.Guid WorksEleFatherId { get; set; }
        public string FatherNodeName { get; set; }
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Attr { get; set; }
        public string WorkContent { get; set; }
        public string Unit { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceLow { get; set; }
        public Nullable<double> PriceHigh { get; set; }
        public string QtyFormula { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<bool> Major { get; set; }
        public string Code { get; set; }
        public string Specialty { get; set; }
        public string ListingIdentity { get; set; }
        public string Remark { get; set; }
        public Nullable<double> OriginalPrice { get; set; }
        public Nullable<double> OriginalRate { get; set; }
        public Nullable<double> OriginalTotal { get; set; }
        public Nullable<int> CalcType { get; set; }
        public Nullable<int> SortNum { get; set; }
        public Nullable<System.Guid> MainProjectId { get; set; }
        public Nullable<System.Guid> SectionalWorksId { get; set; }
    }
}
