//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XML_ProjectReplenishTypeConfigItem
    {
        public int ID { get; set; }
        public Nullable<int> ConfigId { get; set; }
        public string Name { get; set; }
        public Nullable<int> FatherId { get; set; }
        public int itemType { get; set; }
        public int autoAnalysis { get; set; }
    }
}
