//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoResolveService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XmlProjectFeatureSZWasteManage
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public string One { get; set; }
        public string Two { get; set; }
        public string Three { get; set; }
        public string ThreeRemark { get; set; }
        public Nullable<int> BelongProvince { get; set; }
        public Nullable<int> BelongCity { get; set; }
        public Nullable<int> BelongCounty { get; set; }
        public string SoilRockProject { get; set; }
        public string SteelProject { get; set; }
        public string SteelProjectRemark { get; set; }
        public string ConcreteProject { get; set; }
        public string ManageAbility { get; set; }
        public string volume { get; set; }
    }
}
